app/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from core.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^do_logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^error/$', views.ErrorView.as_view(), name='err'),
    url(r'^club/', include('core.club.urls', namespace='club')),
    url(r'^member/', include('core.member.urls', namespace='member')),
    url(r'^documents/', include('core.documents.urls', namespace='docs')),
    url(r'^setting/', include('core.socialsetting.urls', namespace='setting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/club/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ClubDetailView.as_view(), name='view'),
    url(r'^edit/$', views.ClubEditView.as_view(), name='edit'),
]

core/documents/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.DocumentsView.as_view(), name='view'),
    url(r'^delete/(?P<pk>\d+)$', views.DocumentDelete.as_view(), name='delete'),
]

core/member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.MemberListView.as_view(), name='view'),
    url(r'^add/$', views.MemberAddView.as_view(), name='add'),
    url(r'^detail/(?P<pk>\d+)$', views.MemberDetailView.as_view(), name='detail'),
    url(r'^edit/(?P<pk>\d+)$', views.MemberEditView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', views.MemberDeleteView.as_view(), name='delete'),
]

core/club/models.py
from django.db import models

# Create your models here.

core/documents/models.py
from django.db import models

# Create your models here.

core/member/models.py
from django.db import models

# Create your models here.

core/orm/models.py
from django.db import models
from django.contrib.auth.models import User
import time
import os

CITY_CHOICES = (
    ('Mataram', 'Mataram'),
    ('Lombok Barat', 'Lombok Barat'),
    ('Lombok Tengah', 'Lombok Tengah'),
    ('Lombok Timur', 'Lombok Timur'),
    ('Lombok Utara', 'Lombok Utara'),
    ('Sumbawa', 'Sumbawa'),
    ('Sumbawa Barat', 'Sumbawa Barat'),
    ('Bima', 'Bima'),
    ('Dompu', 'Dompu'),
)


def file_profile(instance, filename):
    ext = filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "%s.%s" % (str(milis), ext)
    return os.path.join('user/profile', filename)


def file_club(instance, filename):
    name, ext = filename.split('.')[0], filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "%s_%s.%s" % (name, str(milis), ext)
    return 'club/docs/{0}/{1}'.format(instance.club.id, filename)


def file_club_thumbnail(instance, filename):
    name, ext = filename.split('.')[0], filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "thumbnail_%s_%s.%s" % (name, str(milis), ext)
    return 'club/docs/{0}/thumnail/{1}'.format(instance.club.id, filename)


def file_member(instance, filename):
    ext = filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "user_%s_%s.%s" % (str(instance.user.id), str(milis), ext)
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'city'
        ordering = ['id']


class Club(models.Model):
    name = models.CharField(max_length=100)
    register_number = models.CharField(max_length=100, blank=True, null=True)
    since = models.CharField(max_length=100, blank=True, null=True)
    secretariat = models.TextField(blank=True, null=True)
    city = models.ForeignKey(
        City, on_delete=models.CASCADE, related_name='clubs', blank=True, null=True)
    leader = models.CharField(max_length=100, blank=True, null=True)
    slogan = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to="club/logo",
                             null=True,
                             blank=True,
                             help_text="Upload Logo klub"
                             )

    class Meta:
        db_table = 'club'
        ordering = ['register_number']

    def __str__(self):
        return self.name


class SocialAccount(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField()
    club = models.ForeignKey(
        Club, on_delete=models.CASCADE, related_name='socials')

    class Meta:
        db_table = 'social'

    def __str__(self):
        return self.name


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    club = models.ForeignKey(
        Club, on_delete=models.CASCADE, related_name='members')
    adress = models.TextField(blank=True, null=True)
    gender = models.CharField(max_length=15, blank=True, null=True)
    born_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    draw_length = models.CharField(max_length=5, blank=True, null=True)
    position = models.CharField(max_length=25, blank=True, null=True)
    picture = models.ImageField(upload_to=file_profile,
                                null=True,
                                blank=True,
                                help_text="Upload Potomu sebagai gambar profile",
                                default='user/avatar.png'
                                )

    class Meta:
        db_table = 'member'

    def __str__(self):
        return self.name


class ClubFiles(models.Model):
    uploaded = models.DateTimeField(auto_now=True, auto_now_add=False)
    club = models.ForeignKey(
        Club, on_delete=models.CASCADE, related_name='clubfiles')
    file = models.FileField(upload_to=file_club)
    filename = models.CharField(max_length=30, default=None)
    file_ext = models.CharField(max_length=30, default=None)
    mimetype = models.CharField(max_length=30, default=None)

    class Meta:
        db_table = 'club_files'

    def __str__(self):
        return self.file.name


class MemberFiles(models.Model):
    uploaded = models.DateTimeField(auto_now=True, auto_now_add=False)
    file = models.FileField(upload_to=file_member)

    class Meta:
        db_table = 'member_files'

    def __str__(self):
        return self.name

core/socialsetting/models.py
from django.db import models

# Create your models here.

core/club/forms.py
from django import forms
from core.orm.models import Club

class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        exclude = ['']

core/documents/forms.py
from django import forms
from core.orm.models import ClubFiles


class ClubFilesForm(forms.ModelForm):

    class Meta:
        model = ClubFiles
        fields = ['file']

core/member/forms.py
from django import forms
from core.orm.models import Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        exclude = ['user', 'club']

core/socialsetting/forms.py
from django import forms
from core.orm.models import SocialAccount

class SocialAccountForm(forms.ModelForm):
    class Meta:
        model = SocialAccount
        exclude = ['club']

core/club/views.py
from django.shortcuts import render
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredListView,
    LoginRequiredDetailView,
    LoginRequiredUpdateView,
    LoginRequiredTemplateView,
    LoginRequiredCreateView
)
from utils.datediff import get_age_category
from django.http import HttpResponse
from .forms import ClubForm
from core.orm.models import City, Member

# Create your views here.


class ClubDetailView(LoginRequiredTemplateView):
    template_name = 'core/club/club_detail.html'

    def get(self, request):
        age_category_list = [get_age_category(
            x[0]) for x in Member.objects.all().values_list('born_date')]
        club = request.user.member.club
        data = {
            'menu': 'club',
            'subtitle': 'Detail Klub',
            'member': {
                'total': club.members.all().count(),
                'coach_total': club.members.all().filter(position='Coach').count(),
                'male_total': club.members.filter(gender='pria').count(),
                'female_total': club.members.filter(gender='wanita').count(),
                'anak': len([x for x in age_category_list if x == 'Anak']),
                'remaja': len([x for x in age_category_list if x == 'Remaja']),
                'dewasa': len([x for x in age_category_list if x == 'Dewasa']),
            }
        }
        return render(request, self.template_name, data)


class ClubEditView(LoginRequiredUpdateView):
    template_name = 'core/club/club_edit.html'
    form_class = ClubForm
    success_url = '/club/'

    def get(self, request):
        data = {
            'menu': 'club',
            'subtitle': 'Ubah Informasi Klub',
            'citys': City.objects.all()
        }
        return render(request, self.template_name, data)

    def get_object(self):
        return self.request.user.member.club

    def form_valid(self, form):
        self.object = form.save()
        return super(ClubEditView, self).form_valid(form)

core/documents/views.py
from django.shortcuts import render, redirect
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredListView,
    LoginRequiredDetailView,
    LoginRequiredUpdateView,
    LoginRequiredTemplateView,
    LoginRequiredCreateView
)
from django.http import HttpResponse
from .forms import ClubFilesForm
from core.orm.models import ClubFiles
from datetime import datetime
import mimetypes
import os


class DocumentsView(LoginRequiredGenericView):
    template_name = 'core/docs/docs.html'

    def get(self, request):
        data = {
            'menu': 'docs',
            'subtitle': 'Semua Berkas Klub'
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = ClubFilesForm(request.POST or None, request.FILES)
        if form.is_valid():
            club_file = ClubFiles()
            club_file.club = request.user.member.club
            club_file.file = form.cleaned_data['file']
            club_file.mimetype = mimetypes.guess_type(
                club_file.file.name)[0].split('/')[0]
            club_file.file_ext = mimetypes.guess_type(
                club_file.file.name)[0].split('/')[1]
            club_file.filename = club_file.file.name

            club_file.save()

            return HttpResponse('Success')
        return self.get(request)


class DocumentDelete(LoginRequiredGenericView):

    def get(self, request, pk):
        obj = ClubFiles.objects.get(pk=pk)
        if obj:
            img_url = os.path.join(os.getcwd(), obj.file.url[1:])
            obj.delete()
            if os.path.exists(img_url):
                os.remove(img_url)
                
            return redirect('/documents/')

core/member/views.py
from django.shortcuts import render, redirect
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredListView,
    LoginRequiredDetailView,
    LoginRequiredUpdateView,
    LoginRequiredTemplateView,
    LoginRequiredCreateView
)
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from core.orm.models import Member
from django.contrib.auth.models import User
from .forms import MemberForm
from django.db.models import Q
from django.contrib import messages

# Create your views here.


class MemberListView(LoginRequiredListView):
    template_name = 'core/member/member_list.html'
    model = Member
    paginate_by = 10

    def get_queryset(self):
        q = self.request.GET.get('q', None)
        if q:
            messages.add_message(self.request, messages.INFO, q)
            return Member.objects.filter(Q(club=self.request.user.member.club) &
                                         Q(name__contains=q) |
                                         Q(gender__contains=q) |
                                         Q(user__username__contains=q))

        return Member.objects.filter(club=self.request.user.member.club)

    def get_context_data(self, **kwargs):
        context = super(MemberListView, self).get_context_data(**kwargs)
        context['menu'] = 'member'
        context['subtitle'] = 'Semua Anggota'
        return context


class MemberDetailView(LoginRequiredTemplateView):
    template_name = 'core/member/member_detail.html'

    def get_context_data(self, **kwargs):
        context = super(MemberDetailView, self).get_context_data(**kwargs)
        context['menu'] = 'member'
        context['subtitle'] = 'Detail Anggota'
        context['member'] = Member.objects.get(
            club=self.request.user.member.club, pk=kwargs.get('pk'))

        return context


class MemberAddView(LoginRequiredCreateView):
    template_name = 'core/member/member_add.html'
    form_class = MemberForm
    success_url = '/member/'

    def get(self, request, **kwargs):
        data = {
            'menu': 'member',
            'subtitle': 'Tambah Anggota Baru'
        }
        return render(request, self.template_name, data)

    def form_valid(self, form):
        obj = form.save(commit=False)

        user = User()
        user.username = self.request.POST['username']
        user.set_password(self.request.POST['password'])
        if not self.request.POST.get('staff', None) == None:
            user.is_staff = True
        user.save()

        obj.user = user
        obj.club = self.request.user.member.club
        obj.save()

        return HttpResponseRedirect(reverse_lazy('member:detail', kwargs={'pk': obj.id}))


class MemberEditView(LoginRequiredUpdateView):
    template_name = 'core/member/member_edit.html'
    form_class = MemberForm
    success_url = '/member/'

    def get(self, request, **kwargs):
        data = {
            'menu': 'member',
            'subtitle': 'Ubah Informasi Anggota',
            'member': self.get_object()
        }

        return render(request, self.template_name, data)

    def get_object(self):
        return Member.objects.get(club=self.request.user.member.club, pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        user = self.object.user
        user.username = self.request.POST.get('username')
        if not self.request.POST.get('passwd_change', 'off') == 'off':
            user.set_password(request.POST['password'])

        if not self.request.POST.get('staff', None) == None:
            user.is_staff = True

        user.save()
        obj.save()

        return HttpResponseRedirect(reverse_lazy('member:detail', kwargs={'pk': self.object.id}))


class MemberDeleteView(LoginRequiredGenericView):

    def get(self, request, **kwargs):
        member = Member.objects.get(pk=kwargs.get('pk'))
        if member:
            member.delete()

            return redirect('member:view')

core/socialsetting/views.py
from django.shortcuts import render, redirect
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredCreateView,
    LoginRequiredUpdateView,
)
from core.orm.models import SocialAccount
from .forms import SocialAccountForm
# Create your views here.


class SocialSettingView(LoginRequiredCreateView):
    template_name = 'core/socialsetting/social_setting.html'
    form_class = SocialAccountForm

    def get(self, request):
        data = {
            'menu': 'setting',
            'subtitle': 'Tambah',
            'social_list': SocialAccount.objects.all()
        }

        return render(request, self.template_name, data)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.club = self.request.user.member.club
        obj.save()

        return redirect('setting:view')

    def form_invalid(self):
        return self.get(request)


class SocialSettingEditView(LoginRequiredUpdateView):
    template_name = 'core/socialsetting/social_setting_edit.html'
    form_class = SocialAccountForm

    def get(self, request, **kwargs):
        data = {
            'menu': 'setting',
            'subtitle': 'Tambah',
            'object': self.get_object,
            'social_list': SocialAccount.objects.all()
        }

        return render(request, self.template_name, data)

    def get_object(self):
        return SocialAccount.objects.get(pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()

        return redirect('setting:view')

    def form_invalid(self):
        return self.get(request)


class SocialSettingDeleteView(LoginRequiredGenericView):

    def get(self, request, pk):
        object = SocialAccount.objects.get(pk=pk)
        if object:
            object.delete()
            return redirect('setting:view')

templates/core/socialsetting/social_setting.html
{% extends "base/base.html" %} {% load staticfiles %} {% block content %}
<div class="row">
    <div class="col-md-3">
        <div class="box box-success">
            <div class="box-header with-border">
                Tambahkan Akun Media Klub
            </div>
            <div class="box-body">
                <form action="{% url 'setting:view' %}" method="POST">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="name">Keterangan / Label</label>
                        <input type="text" required name="name" value="" class="form-control" placeholder="ex : Website">
                    </div>
                    <div class="form-group">
                        <label for="url">Alamat Situs</label>
                        <textarea rows="2" cols="" class="form-control" name="url" placeholder="ex : google.com"></textarea>
                    </div>

                    <div class="form-group">
                        <div class="pull-right">
                            <button type="reset" class="btn btn-danger">Reset</button>
                            <button type="submit" class="btn btn-success" style="margin-left: 8px;">Simpan</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="box box-success">
            <div class="box-header with-border">
                List Akun Media Klub
            </div>
            <div class="box-body">
                <table class="table table-striped table-hovered">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Alamat Situs</th>
                            <th style="text-align: center">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for social in social_list %}
                        <tr>
                            <td style="width: 5%">{{forloop.counter}}</td>
                            <td style="width: 30%">{{social.name}}</td>
                            <td><a href="{{social.url}}">{{social.url}}</a></td>
                            <td style="width: 10%">
                                <div class="btn-group">
                                    <a href="{% url 'setting:edit' social.pk %}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                    <a href="{% url 'setting:delete' social.pk %}" class="btn btn-danger" onclick="return confirm('Ingin menghapus data ini?')"><i class="fa fa-trash"></i></a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/core/socialsetting/social_setting_edit.html
{% extends "base/base.html" %} {% load staticfiles %} {% block content %}
<div class="row">
    <div class="col-md-3">
        <div class="box box-success">
            <div class="box-header with-border">
                Tambahkan Akun Media Klub
            </div>
            <div class="box-body">
                <form action="{% url 'setting:edit' object.pk %}" method="POST">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="name">Keterangan / Label</label>
                        <input type="text" required name="name" value="{{object.name}}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="url">Alamat Situs</label>
                        <textarea rows="2" cols="" class="form-control" name="url">{{object.url}}</textarea>
                    </div>

                    <div class="form-group">
                        <div class="pull-right">
                            <a href="/setting/" type="reset" class="btn btn-danger">Batal</a>
                            <button type="submit" class="btn btn-success" style="margin-left: 8px;">Update</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="box box-success">
            <div class="box-header with-border">
                List Akun Media Klub
            </div>
            <div class="box-body">
                <table class="table table-striped table-hovered">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Alamat Situs</th>
                            <th style="text-align: center">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for social in social_list %}
                        <tr>
                            <td style="width: 5%">{{forloop.counter}}</td>
                            <td style="width: 30%">{{social.name}}</td>
                            <td><a href="{{social.url}}">{{social.url}}</a></td>
                            <td style="width: 10%">
                                <div class="btn-group">
                                    <a href="{% url 'setting:edit' social.pk %}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                    <a href="{% url 'setting:delete' social.pk %}" class="btn btn-danger" onclick="return confirm('Ingin menghapus data ini?')"><i class="fa fa-trash"></i></a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}