app/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from core.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^do_logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^error/$', views.ErrorView.as_view(), name='err'),
    url(r'^club/', include('core.club.urls', namespace='club')),
    url(r'^member/', include('core.member.urls', namespace='member')),
    url(r'^documents/', include('core.documents.urls', namespace='docs')),
    url(r'^setting/', include('core.socialsetting.urls', namespace='setting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.MemberListView.as_view(), name='view'),
    url(r'^add/$', views.MemberAddView.as_view(), name='add'),
    url(r'^detail/(?P<pk>\d+)$', views.MemberDetailView.as_view(), name='detail'),
    url(r'^edit/(?P<pk>\d+)$', views.MemberEditView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', views.MemberDeleteView.as_view(), name='delete'),
]

templates/core/docs/docsview/docs_filedoc.html
{% load staticfiles %}

<style>
    .bordered-img {
        position: relative;
        border: 1px #d5d5d5 solid;
        width: 100%;
        height: 50%;
    }

    img:hover{
        cursor: pointer;
    }

    .center{
        display: table; 
        margin: 0 auto;
    }

    p{
        text-align: center;
    }
</style>
<div class="row">
    {% for file in request.user.member.club.clubfiles.all %} 
    {% if not file.mimetype == 'image' %}
      {% if file.file_ext == 'msword' %} 
        <div class="col-md-2 center" style="margin-bottom: 16px;">
            <img id="image" class="bordered-img" src="{% static 'images/word.png' %}" onclick="imgClick('{{file.file.url}}')">
            <p>{{file.filename}}</p>
        </div>
    {% elif file.file_ext == 'msexcel' %}
        <div class="col-md-2 center" style="margin-bottom: 16px;">
            <img id="image" class="bordered-img" src="{% static 'images/excel.png' %}" onclick="imgClick('{{file.file.url}}')">
            <p>{{file.filename}}</p>
        </div>
    {% elif file.file_ext == 'pdf' %}
        <div class="col-md-2 center" style="margin-bottom: 16px;">
            <img id="image" class="bordered-img" src="{% static 'images/pdf.png' %}" onclick="imgClick('{{file.file.url}}')">
            <p>{{file.filename}}</p>
        </div>
    {% else %}
        <div class="col-md-2 center" style="margin-bottom: 16px;">
            <img id="image" class="bordered-img" src="{% static 'images/document.png' %}" onclick="imgClick('{{file.file.url}}')">
            <p>{{file.filename}}</p>
        </div>
    {% endif %} 
    {% endif %}
    {% endfor %}
</div>

<script>
    function imgClick(url){
        window.open(url, '_blank')
    }
</script>

templates/core/docs/docsview/docs_image.html
{% load thumbnail %}

<style>
    img:hover {
        cursor: pointer;
    }

    .center {
        display: table;
        margin: 0 auto;
    }

    .thumbnail img {
        position: absolute;
        left: 50%;
        top: 50%;
        height: 145px;
        width: auto;
        -webkit-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
    }

    .thumbnail {
        position: relative;
        height: 200px;
        overflow: hidden
    }
</style>
<div class="row">
    {% for file in request.user.member.club.clubfiles.all %} {% if file.mimetype == 'image' %}
    <div class="col-md-3 col-xs-12 center thumbnail" style="margin-bottom: 16px; position: relative;">
        <img src="{{ file.file.url }}" onclick="imgClick('{{file.file.url}}')">
        <a href="{% url 'docs:delete' pk=file.pk %}" class="center" onclick="return confirm('Anda yakin ingin menghapus file ini?')">Hapus [x]</a>
        <p style="position: absolute; bottom: 3px; text-align: center" class="center">{{file.filename}}</p>
    </div>
    {% endif %} {% endfor %}
</div>

<script>
    function imgClick(url) {
        window.open(url, '_blank')
    }
</script>