app/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from core.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^do_logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^error/$', views.ErrorView.as_view(), name='err'),
    url(r'^club/', include('core.club.urls', namespace='club')),
    url(r'^member/', include('core.member.urls', namespace='member')),
    url(r'^documents/', include('core.documents.urls', namespace='docs')),
    url(r'^setting/', include('core.socialsetting.urls', namespace='setting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.MemberListView.as_view(), name='view'),
    url(r'^add/$', views.MemberAddView.as_view(), name='add'),
    url(r'^detail/(?P<pk>\d+)$', views.MemberDetailView.as_view(), name='detail'),
    url(r'^edit/(?P<pk>\d+)$', views.MemberEditView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', views.MemberDeleteView.as_view(), name='delete'),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% include "base/static.html" %}
</head>

<body class="hold-transition skin-green layout-top-nav">
    {% include "base/navbar.html" %}

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
           <h1 class="bg-success" style="padding: 8px;">{{subtitle}}</h1>
        </section>
        <!-- Main content -->
        <section class="content">
            {% block content %} {% endblock content %}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    {% block js %} {% endblock js %}
</body>

{% include "base/footer.html" %}

</html>

templates/base/error.html
<style>
    .card-container {
        display: table;
        margin: 0 auto;
    }

    .card {
        position: relative;
        -webkit-box-shadow: 0px 3px 15px 0px rgba(0, 0, 0, 0.13);
        -moz-box-shadow: 0px 3px 15px 0px rgba(0, 0, 0, 0.13);
        box-shadow: 0px 3px 15px 0px rgba(0, 0, 0, 0.13);
        padding: 16px;
    }

    .card > a{
        display: table;
        margin: 0 auto;
    }
</style>

<div class="card-container">
    <div class="card">
        <h3>Maaf Anda tidak diizinkan untuk mengakses halaman ini</h3>
        <a href="{% url 'logout' %}">Menuju Halaman Login</a>
    </div>
</div>

templates/base/footer.html
<footer class="main-footer">
    <div class="container">
        <strong>Powered by &copy; <a href="https://arrihuarchery.id">Arrihu Archery Team</a></strong>
    </div>
    <!-- /.container -->
</footer>

templates/base/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% include "base/static.html" %}
</head>
{% comment %} {% autoescape off %} {% endcomment %}

<body class="hold-transition skin-green layout-top-nav">

    <header class="main-header">
        <nav class="navbar navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand"></a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <i class="fa fa-bars"></i>
          </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="#">Website Perpani NTB &nbsp; <i class="fa fa-globe"></i></a></li>
                        <li class=""><a href="#" onclick="showModal()">Login &nbsp; <i class="fa fa-sign-in"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container">
                <h2>PERPANI NTB <small>Club</small></h2>
                <h6 style="text-align: justify"></h6>
            </div>
        </section>
        <section class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-blue"><i class="fa fa-users"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">Total Klub</span>
                                <span class="info-box-number">{{club.total}}</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-red"><i class="fa fa-user"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">Total Pemanah</span>
                                <span class="info-box-number">{{member.total}}</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->

                    <!-- fix for small devices only -->
                    <div class="clearfix visible-sm-block"></div>

                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-user"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">Total Pelatih</span>
                                <span class="info-box-number">{{member.coach_total}}</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">New Members</span>
                                <span class="info-box-number">2,000</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-md-6">
                        <div class="box box-success">
                            <div class="box-header with-border">
                                <h5>Statistik Klub Berdasarkan Kab./Kota</h5>
                            </div>
                            <div class="box-body">
                                <canvas id="pieChart" width="400" height="237"></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box box-success">
                            <div class="box-header with-border">
                                <h5>Statistik Berdasarkan Anggota Terdaftar per Klub</h5>
                            </div>
                            <div class="box-body">
                                <canvas id="dounatChart" width="400" height="237"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

    <div id="modal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <form class="modal-content" method="POST" action=".">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h5 class="modal-title">Login Untuk Mengelola Clubmu</h5>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="" class="control-label">Username</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label for="" class="control-label">Password</label>
                        <input type="password" class="form-control" name="password">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success btn-outline">Login <i class="fa fa-sign-in"></i></button>
                </div>
            </form>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

    {% if messages %} {% for message in messages %} {% if message.tags == 'warning' %}
    <script>
        toastr.error('{{message}}')
    </script>
    {% endif %} {% endfor %} {% endif %}

    <script>
        function showModal() {
            $('#modal').modal()
        }

        var bgColor = [
            'rgba(255, 206, 86, 0.7)',
            'rgba(75, 192, 192, 0.7)',
            'rgba(153, 102, 255, 0.7)',
            'rgba(153, 45, 89, 0.7)',
            'rgba(19, 102, 13, 0.7)',
            'rgba(5, 237, 255, 0.7)',
            'rgba(8, 155, 255, 0.7)',
            'rgba(114, 114, 255, 0.7)',
            'rgba(155, 55, 1, 0.7)',
            'rgba(237, 34, 255, 0.7)',
        ]

        var options = {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }

        var pieContainer = document.getElementById("pieChart").getContext('2d');
        var chart = new Chart(pieContainer, {
            type: 'pie',
            data: {
                labels: {{citys.labels | safe}},
                datasets: [{
                    label: '# of Votes',
                    data: {{ citys.values | safe}},
                    backgroundColor: bgColor,
                    borderWidth: 0
                }]
            },
            options: ''
        });

        var dounatContainer = document.getElementById("dounatChart").getContext('2d');
        var dounatChart = new Chart(dounatContainer, {
            type: 'polarArea',
            data: {
                labels: {{club.labels | safe }},
                datasets: [{
                    label: '# of Votes',
                    data: {{ club.member_count | safe}},
                    backgroundColor: bgColor,
                    borderWidth: 0
                }]
            },
            options: options
        });
    </script>
</body>
{% comment %} {% endautoescape %} {% endcomment %}

{% include "base/footer.html" %}

</html>

templates/base/navbar.html
{% load staticfiles %}
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="navbar-header">
            <a href="#" class="navbar-brand"><b>{{request.user.member.club.name}}</b></a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <i class="fa fa-bars"></i>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="{% if menu == 'club' %}active-nav active{%endif%}"><a href="/club/">Klub &nbsp; <i class="fa fa-users"></i></a></li>
                <li class="{% if menu == 'member' %}active-nav active{%endif%}"><a href="/member/">Anggota &nbsp; <i class="fa fa-user"></i></a></li>
                <li class="{% if menu == 'docs' %}active-nav active{%endif%}"><a href="/documents/">Berkas &nbsp; <i class="fa fa-files-o"></i></a></li>
                <li class="{% if menu == 'setting' %}active-nav active{%endif%}"><a href="/setting/">Pengaturan &nbsp; <i class="fa fa-cog"></i></a></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{request.user.member.picture.url}}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{request.user.member.name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{request.user.member.picture.url}}" class="img-circle" alt="User Image">

                            <p>
                                {{request.user.member.name}} - {{request.user.member.position}}
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{% url 'member:detail' request.user.member.pk %}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{% url 'logout' %}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-custom-menu -->
    </nav>
</header>
<!-- <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Title</span>
     <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="">Tentang Aplikasi</a>
    </nav> 
</div> -->

templates/base/static.html
{% load staticfiles %}

<link rel="stylesheet" type="" href="{% static 'libs/bs/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="" href="{% static 'libs/alte/css/AdminLTE.min.css' %}">
<link rel="stylesheet" type="" href="{% static 'libs/alte/css/skins/_all-skins.min.css' %}">
<link rel="stylesheet" type="" href="{% static 'libs/fa/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="" href="{% static 'libs/datepicker/datepicker.min.css' %}">
<link rel="stylesheet" type="" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<link rel="stylesheet" href="{% static 'libs/dropzone/dropzone.min.css' %}">

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/Chart.min.js' %}"></script>
<script src="{% static 'libs/bs/js/bootstrap.min.js' %}"></script>
<script src="{% static 'libs/alte/js/app.min.js' %}"></script>
<script src="{% static 'libs/alte/js/demo.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="{% static 'libs/dropzone/dropzone.min.js' %}"></script>
<script src="{% static 'libs/datepicker/datepicker.min.js' %}"></script>