app/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from core.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^do_logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^error/$', views.ErrorView.as_view(), name='err'),
    url(r'^club/', include('core.club.urls', namespace='club')),
    url(r'^member/', include('core.member.urls', namespace='member')),
    url(r'^documents/', include('core.documents.urls', namespace='docs')),
    url(r'^setting/', include('core.socialsetting.urls', namespace='setting')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/club/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ClubDetailView.as_view(), name='view'),
    url(r'^edit/$', views.ClubEditView.as_view(), name='edit'),
]

core/documents/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.DocumentsView.as_view(), name='view'),
    url(r'^delete/(?P<pk>\d+)$', views.DocumentDelete.as_view(), name='delete'),
]

core/member/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.MemberListView.as_view(), name='view'),
    url(r'^add/$', views.MemberAddView.as_view(), name='add'),
    url(r'^detail/(?P<pk>\d+)$', views.MemberDetailView.as_view(), name='detail'),
    url(r'^edit/(?P<pk>\d+)$', views.MemberEditView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', views.MemberDeleteView.as_view(), name='delete'),
]

core/club/models.py
from django.db import models

# Create your models here.

core/documents/models.py
from django.db import models

# Create your models here.

core/member/models.py
from django.db import models

# Create your models here.

core/orm/models.py
from django.db import models
from django.contrib.auth.models import User
import time
import os

CITY_CHOICES = (
    ('Mataram', 'Mataram'),
    ('Lombok Barat', 'Lombok Barat'),
    ('Lombok Tengah', 'Lombok Tengah'),
    ('Lombok Timur', 'Lombok Timur'),
    ('Lombok Utara', 'Lombok Utara'),
    ('Sumbawa', 'Sumbawa'),
    ('Sumbawa Barat', 'Sumbawa Barat'),
    ('Bima', 'Bima'),
    ('Dompu', 'Dompu'),
)


def file_profile(instance, filename):
    ext = filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "%s.%s" % (str(milis), ext)
    return os.path.join('user/profile', filename)


def file_club(instance, filename):
    name, ext = filename.split('.')[0], filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "%s_%s.%s" % (name, str(milis), ext)
    return 'club/docs/{0}/{1}'.format(instance.club.id, filename)


def file_club_thumbnail(instance, filename):
    name, ext = filename.split('.')[0], filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "thumbnail_%s_%s.%s" % (name, str(milis), ext)
    return 'club/docs/{0}/thumnail/{1}'.format(instance.club.id, filename)


def file_member(instance, filename):
    ext = filename.split('.')[-1]
    milis = int(round(time.time()))
    filename = "user_%s_%s.%s" % (str(instance.user.id), str(milis), ext)
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'city'
        ordering = ['id']


class Club(models.Model):
    name = models.CharField(max_length=100)
    register_number = models.CharField(max_length=100, blank=True, null=True)
    since = models.CharField(max_length=100, blank=True, null=True)
    secretariat = models.TextField(blank=True, null=True)
    city = models.ForeignKey(
        City, on_delete=models.CASCADE, related_name='clubs', blank=True, null=True)
    leader = models.CharField(max_length=100, blank=True, null=True)
    slogan = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to="club/logo",
                             null=True,
                             blank=True,
                             help_text="Upload Logo klub"
                             )

    class Meta:
        db_table = 'club'
        ordering = ['register_number']

    def __str__(self):
        return self.name


class SocialAccount(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField()
    club = models.ForeignKey(
        Club, on_delete=models.CASCADE, related_name='socials')

    class Meta:
        db_table = 'social'

    def __str__(self):
        return self.name


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    club = models.ForeignKey(
        Club, on_delete=models.CASCADE, related_name='members')
    adress = models.TextField(blank=True, null=True)
    gender = models.CharField(max_length=15, blank=True, null=True)
    born_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    draw_length = models.CharField(max_length=5, blank=True, null=True)
    position = models.CharField(max_length=25, blank=True, null=True)
    picture = models.ImageField(upload_to=file_profile,
                                null=True,
                                blank=True,
                                help_text="Upload Potomu sebagai gambar profile",
                                default='user/avatar.png'
                                )

    class Meta:
        db_table = 'member'

    def __str__(self):
        return self.name


class ClubFiles(models.Model):
    uploaded = models.DateTimeField(auto_now=True, auto_now_add=False)
    club = models.ForeignKey(
        Club, on_delete=models.CASCADE, related_name='clubfiles')
    file = models.FileField(upload_to=file_club)
    filename = models.CharField(max_length=30, default=None)
    file_ext = models.CharField(max_length=30, default=None)
    mimetype = models.CharField(max_length=30, default=None)

    class Meta:
        db_table = 'club_files'

    def __str__(self):
        return self.file.name


class MemberFiles(models.Model):
    uploaded = models.DateTimeField(auto_now=True, auto_now_add=False)
    file = models.FileField(upload_to=file_member)

    class Meta:
        db_table = 'member_files'

    def __str__(self):
        return self.name

core/socialsetting/models.py
from django.db import models

# Create your models here.

core/club/forms.py
from django import forms
from core.orm.models import Club

class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        exclude = ['']

core/documents/forms.py
from django import forms
from core.orm.models import ClubFiles


class ClubFilesForm(forms.ModelForm):

    class Meta:
        model = ClubFiles
        fields = ['file']

core/member/forms.py
from django import forms
from core.orm.models import Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        exclude = ['user', 'club']

core/socialsetting/forms.py
from django import forms
from core.orm.models import SocialAccount

class SocialAccountForm(forms.ModelForm):
    class Meta:
        model = SocialAccount
        exclude = ['club']

core/club/views.py
from django.shortcuts import render
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredListView,
    LoginRequiredDetailView,
    LoginRequiredUpdateView,
    LoginRequiredTemplateView,
    LoginRequiredCreateView
)
from utils.datediff import get_age_category
from django.http import HttpResponse
from .forms import ClubForm
from core.orm.models import City, Member

# Create your views here.


class ClubDetailView(LoginRequiredTemplateView):
    template_name = 'core/club/club_detail.html'

    def get(self, request):
        age_category_list = [get_age_category(
            x[0]) for x in Member.objects.all().values_list('born_date')]
        club = request.user.member.club
        data = {
            'menu': 'club',
            'subtitle': 'Detail Klub',
            'member': {
                'total': club.members.all().count(),
                'coach_total': club.members.all().filter(position='Coach').count(),
                'male_total': club.members.filter(gender='pria').count(),
                'female_total': club.members.filter(gender='wanita').count(),
                'anak': len([x for x in age_category_list if x == 'Anak']),
                'remaja': len([x for x in age_category_list if x == 'Remaja']),
                'dewasa': len([x for x in age_category_list if x == 'Dewasa']),
            }
        }
        return render(request, self.template_name, data)


class ClubEditView(LoginRequiredUpdateView):
    template_name = 'core/club/club_edit.html'
    form_class = ClubForm
    success_url = '/club/'

    def get(self, request):
        data = {
            'menu': 'club',
            'subtitle': 'Ubah Informasi Klub',
            'citys': City.objects.all()
        }
        return render(request, self.template_name, data)

    def get_object(self):
        return self.request.user.member.club

    def form_valid(self, form):
        self.object = form.save()
        return super(ClubEditView, self).form_valid(form)

core/documents/views.py
from django.shortcuts import render, redirect
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredListView,
    LoginRequiredDetailView,
    LoginRequiredUpdateView,
    LoginRequiredTemplateView,
    LoginRequiredCreateView
)
from django.http import HttpResponse
from .forms import ClubFilesForm
from core.orm.models import ClubFiles
from datetime import datetime
import mimetypes
import os


class DocumentsView(LoginRequiredGenericView):
    template_name = 'core/docs/docs.html'

    def get(self, request):
        data = {
            'menu': 'docs',
            'subtitle': 'Semua Berkas Klub'
        }
        return render(request, self.template_name, data)

    def post(self, request):
        form = ClubFilesForm(request.POST or None, request.FILES)
        if form.is_valid():
            club_file = ClubFiles()
            club_file.club = request.user.member.club
            club_file.file = form.cleaned_data['file']
            club_file.mimetype = mimetypes.guess_type(
                club_file.file.name)[0].split('/')[0]
            club_file.file_ext = mimetypes.guess_type(
                club_file.file.name)[0].split('/')[1]
            club_file.filename = club_file.file.name

            club_file.save()

            return HttpResponse('Success')
        return self.get(request)


class DocumentDelete(LoginRequiredGenericView):

    def get(self, request, pk):
        obj = ClubFiles.objects.get(pk=pk)
        if obj:
            img_url = os.path.join(os.getcwd(), obj.file.url[1:])
            obj.delete()
            if os.path.exists(img_url):
                os.remove(img_url)
                
            return redirect('/documents/')

core/member/views.py
from django.shortcuts import render, redirect
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredListView,
    LoginRequiredDetailView,
    LoginRequiredUpdateView,
    LoginRequiredTemplateView,
    LoginRequiredCreateView
)
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from core.orm.models import Member
from django.contrib.auth.models import User
from .forms import MemberForm
from django.db.models import Q
from django.contrib import messages

# Create your views here.


class MemberListView(LoginRequiredListView):
    template_name = 'core/member/member_list.html'
    model = Member
    paginate_by = 10

    def get_queryset(self):
        q = self.request.GET.get('q', None)
        if q:
            messages.add_message(self.request, messages.INFO, q)
            return Member.objects.filter(Q(club=self.request.user.member.club) &
                                         Q(name__contains=q) |
                                         Q(gender__contains=q) |
                                         Q(user__username__contains=q))

        return Member.objects.filter(club=self.request.user.member.club)

    def get_context_data(self, **kwargs):
        context = super(MemberListView, self).get_context_data(**kwargs)
        context['menu'] = 'member'
        context['subtitle'] = 'Semua Anggota'
        return context


class MemberDetailView(LoginRequiredTemplateView):
    template_name = 'core/member/member_detail.html'

    def get_context_data(self, **kwargs):
        context = super(MemberDetailView, self).get_context_data(**kwargs)
        context['menu'] = 'member'
        context['subtitle'] = 'Detail Anggota'
        context['member'] = Member.objects.get(
            club=self.request.user.member.club, pk=kwargs.get('pk'))

        return context


class MemberAddView(LoginRequiredCreateView):
    template_name = 'core/member/member_add.html'
    form_class = MemberForm
    success_url = '/member/'

    def get(self, request, **kwargs):
        data = {
            'menu': 'member',
            'subtitle': 'Tambah Anggota Baru'
        }
        return render(request, self.template_name, data)

    def form_valid(self, form):
        obj = form.save(commit=False)

        user = User()
        user.username = self.request.POST['username']
        user.set_password(self.request.POST['password'])
        if not self.request.POST.get('staff', None) == None:
            user.is_staff = True
        user.save()

        obj.user = user
        obj.club = self.request.user.member.club
        obj.save()

        return HttpResponseRedirect(reverse_lazy('member:detail', kwargs={'pk': obj.id}))


class MemberEditView(LoginRequiredUpdateView):
    template_name = 'core/member/member_edit.html'
    form_class = MemberForm
    success_url = '/member/'

    def get(self, request, **kwargs):
        data = {
            'menu': 'member',
            'subtitle': 'Ubah Informasi Anggota',
            'member': self.get_object()
        }

        return render(request, self.template_name, data)

    def get_object(self):
        return Member.objects.get(club=self.request.user.member.club, pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        user = self.object.user
        user.username = self.request.POST.get('username')
        if not self.request.POST.get('passwd_change', 'off') == 'off':
            user.set_password(request.POST['password'])

        if not self.request.POST.get('staff', None) == None:
            user.is_staff = True

        user.save()
        obj.save()

        return HttpResponseRedirect(reverse_lazy('member:detail', kwargs={'pk': self.object.id}))


class MemberDeleteView(LoginRequiredGenericView):

    def get(self, request, **kwargs):
        member = Member.objects.get(pk=kwargs.get('pk'))
        if member:
            member.delete()

            return redirect('member:view')

core/socialsetting/views.py
from django.shortcuts import render, redirect
from utils.customview import (
    LoginRequiredGenericView,
    LoginRequiredCreateView,
    LoginRequiredUpdateView,
)
from core.orm.models import SocialAccount
from .forms import SocialAccountForm
# Create your views here.


class SocialSettingView(LoginRequiredCreateView):
    template_name = 'core/socialsetting/social_setting.html'
    form_class = SocialAccountForm

    def get(self, request):
        data = {
            'menu': 'setting',
            'subtitle': 'Tambah',
            'social_list': SocialAccount.objects.all()
        }

        return render(request, self.template_name, data)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.club = self.request.user.member.club
        obj.save()

        return redirect('setting:view')

    def form_invalid(self):
        return self.get(request)


class SocialSettingEditView(LoginRequiredUpdateView):
    template_name = 'core/socialsetting/social_setting_edit.html'
    form_class = SocialAccountForm

    def get(self, request, **kwargs):
        data = {
            'menu': 'setting',
            'subtitle': 'Tambah',
            'object': self.get_object,
            'social_list': SocialAccount.objects.all()
        }

        return render(request, self.template_name, data)

    def get_object(self):
        return SocialAccount.objects.get(pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()

        return redirect('setting:view')

    def form_invalid(self):
        return self.get(request)


class SocialSettingDeleteView(LoginRequiredGenericView):

    def get(self, request, pk):
        object = SocialAccount.objects.get(pk=pk)
        if object:
            object.delete()
            return redirect('setting:view')

templates/core/member/member_add.html
{% extends "base/base.html" %} {% load staticfiles %} {% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="box box-success">
            <div class="box-header with-border">
                Tambah Member
            </div>
            <div class="box-body">
                <div class="col-md-3 col-sm-3">
                    <img src="{% static 'images/avatar.png' %}" id="picture" alt="" style="width: 100%; height: auto;">
                    <button class="btn btn-success btn-outline btn-block" style="margin-top: 8px; margin-bottom: 8px;" onclick="document.getElementById('fileInput').click();">Upload Gambar <i class="fa fa-upload"></i></button>
                </div>
                <div class="col-md-9 col-sm-9">
                    <form action="{% url 'member:add' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="username">No. Registrasi Klub</label>
                            <input type="text" required name="username" value="" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" required name="password" value="" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label">Nama</label>
                            <input type="text" class="form-control" name="name" value="" required>
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label">Alamat</label>
                            <textarea name="adress" rows="3" class="form-control" required></textarea>
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label">Jenis Kelamin</label>
                        </div>
                        <div class="form-group">
                            <input required type="radio" name="gender" value="pria"> Pria &nbsp; &nbsp; &nbsp;
                            <input required type="radio" name="gender" value="wanita"> Wanita
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label">Tanggal Lahir</label>
                            <input required type="text" id="datepicker" class="form-control" name="born_date" value="" readonly>
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label">No. HP</label>
                            <input required type="text" class="form-control" name="phone" value="">
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label">Panjang Tarikan (Inch)</label>
                            <input required type="number" step="any" class="form-control" name="draw_length" value="">
                        </div>

                        <div class="form-group">
                            <label for="" class="control-label">Posisi Dalam Klub</label>
                            <select class="form-control" name="position">
                    <option value="Member">Anggota</option>
                    <option value="Coach">Coach</option>
                </select>
                        </div>

                        <div class="form-group">
                            <input id="fileInput" name='picture' type="file" style="display:none;" accept="image/*" />
                        </div>

                        <div class="form-group">
                            <span style="font-size: 10px; color: red">*User dapat menambahkan, mengubah, dan menghapus Anggota dan berkas klub, dan pengaturan grup</span>
                            <label for="" class="control-label">Jadikan User Sebagai Pengelola</label> &nbsp; <input type="checkbox"
                                name="gender" value="wanita">
                        </div>

                        <div class="form-group">
                            <div class="btn-group pull-right">
                                <button type="reset" class="btn btn-danger">Reset</button>
                                <button type="submit" class="btn btn-success" style="margin-left: 8px;">Simpan</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %} {% block js %}
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#picture').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#fileInput").change(function () {
        readURL(this);
    });

    $('#datepicker').datepicker({
        autoclose: true
    })
</script>
{% endblock js %}

templates/core/member/member_detail.html
{% extends "base/base.html" %} {% load staticfiles %} {% block content %} {% if member %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-success">
            <div class="box-header with-border">
                Detai Member : <b>{{member.name}}</b>
            </div>
            <div class="box-body">
                <div class="col-md-3 col-sm-3">
                    <img src="{{member.picture.url}}" alt="" style="width: 100%; height: auto; border: 1px #d5d8dc solid">
                    <p style="text-align: center; font-size: 18px; padding-top: 8px;"><b>{{member.name}}</b></p>
                    <a href="{% url 'member:edit' member.pk %}" class="btn btn-success btn-outline btn-block" style="margin-bottom: 8px">Ubah Info <i class="fa fa-pencil"></i></a>
                </div>
                <div class="col-md-9 col-sm-9">
                    <table class="table table-responsive table-striped table-hover">
                        <tbody>
                            <tr>
                                <td style="width: 30%">Nama</td>
                                <td>:</td>
                                <td>{{member.name}}</td>
                            </tr>
                            <tr>
                                <td style="width: 30%">No. Registrasi Klub</td>
                                <td>:</td>
                                <td>{{member.user.username}}</td>
                            </tr>
                            <tr>
                                <td style="width: 30%">Alamat</td>
                                <td>:</td>
                                <td>{{member.adress}}
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 30%">Jenis Kelamin</td>
                                <td>:</td>
                                <td>{{member.gender}}</td>
                            </tr>
                            <tr>
                                <td style="width: 30%">Tanggal Lahir</td>
                                <td>:</td>
                                <td>{{member.born_date}}
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 30%">No. HP</td>
                                <td>:</td>
                                <td>{{member.phone}}</td>
                            </tr>
                            <tr>
                                <td style="width: 30%">Draw Length</td>
                                <td>:</td>
                                <td>{{member.draw_length}}</td>
                            </tr>
                            <tr>
                                <td style="width: 30%">Posisi</td>
                                <td>:</td>
                                <td>{{member.position}}</td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="/member/add/" class="pull-right" style="margin-left: 16px;">Tambah Anggota &raquo;</a> 
                    <a href="/member/" class="pull-right">&laquo; Kembali</a>
                </div>
            </div>
        </div>
    </div>
</div>
{%else%}
<h6 style="text-align: center">Anggota Tidak Ditemukan</h6>
{% endif %} {% endblock content %}

templates/core/member/member_list.html
{% extends "base/base.html" %} {% load staticfiles %} {% block content %}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if messages %} {% for message in messages %}
        <div class="alert alert-warning alert-dismissible" style="opacity: 0.9">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <p style="text-align: center">Hasil pencarian dengan kata kunci : <b>{{message}}</b></p>
        </div>
        {% endfor %} {% endif %}
        <div class="box box-success">
            <div class="box-header with-border">
                <div class="row">
                    <div class="col-md-4">
                        List anggota
                    </div>
                    <div class="col-md-8">
                        <div class="form-inline">
                            <form class="pull-right" method="GET" action="{% url 'member:view' %}">
                                <div class="form-group">
                                    <input type="text" required name="q" value="" class="form-control" placeholder="Pencarian . . .">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-warning"><i class="fa fa-search"></i></button>
                                    <a href="/member/add/" class="btn btn-success">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    {% for member in object_list %}
                    <li class="item with-border">
                        <div class="product-img">
                            <img src="{{member.picture.url}}" alt="{{member.name}}">
                        </div>
                        <div class="product-info">
                            <a href="#" onclick="showModal('{{member.pk}}')" class="color-danger"><i class="fa fa-trash pull-right"></i></a>                            {% if member.user.is_staff %}
                            <a href="#"><i class="fa fa-star pull-right"></i></a> {% endif %}
                            <a href="{% url 'member:detail' member.pk %}" class="product-title">{{member.name}}<span class="label label-warning {% ifequal member.position 'Coach' %} label-success {%endifequal%} pull-right">{{member.position}}</span></a>
                            <span class="product-description">{{member.user.username}}</span>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

<ul class="pagination" style="display: table; margin: 0 auto;">
    <li {% if not page_obj.has_previous %}class="disabled" {% endif %}>
        <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}" aria-label="Previous" {% endif %}><span aria-hidden="true">&laquo;</span></a>
    </li>
    <!-- <li><a href="?page=1">Pertama</a></li> -->
     {% for linkpage in paginator.page_range %} {% ifequal linkpage page_obj.number %}
    <li class="active">
        <a>{{ page_obj.number }}<span class="sr-only">(current)</span></a>
    </li>
    {% else %}
    <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
    {% endifequal %} {% endfor %} 
    <!-- <li><a href="?page={{ page_obj.paginator.num_pages }}">Terakhir</a></li> -->
    <li {% if not page_obj.has_next %}class="disabled" {% endif %}>
        <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}" aria-label="Next" {% endif %}><span aria-hidden="true">&raquo;</span></a>
    </li>
</ul>


<div class="modal" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Konfirmasi</h4>
            </div>
            <div class="modal-body">
                Yakin nih mau hapus aku? :(
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
                <button type="button" class="btn btn-success" onclick="doDelete()">Hapus</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %} {% block js %}
<script>
    var memberPk = 0

    function showModal(pk) {
        $('#confirmModal').modal();
        memberPk = pk
    }

    function doDelete() {
        location.href = '/member/delete/' + memberPk
    }
</script>
{% endblock js %}